version: "3"
services:
  web:
    build: .
    working_dir: "/usr/src/app"
    ports:
      - "5000:5000"
    volumes:
      - ".:/usr/src/app"
      # Don't sync the node_modules directory back to the client.
      - "/usr/src/app/node_modules"
